### ISSUE TITLE
Crash on Exit when Toast Message Is Up

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#124]
```
What steps will reproduce the problem?
1. Open Witty
2. Toast Message (you have X new tweets!)
3. Close Witty while toast is still up
4. Witty crashes

What is the expected output? What do you see instead?
it should not error. I think the toast notification needs to be close if
witty exits

What version of the product are you using? On what operating system?
0.1.7 beta debug (compiled source code and running debug) - Windows Vista Sp1

Please provide any additional information below.
error log:

2008-04-16 13:54:21,984 [1] ERROR Witty.Logging - Unhandled Exception
System.InvalidOperationException: Cannot set Visibility or call Show or
ShowDialog after window has closed.
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at Witty.MainWindow.PopupClicked(Tweet tweet) in
C:\wittytwitter-read-only\Witty\Witty\MainWindow.xaml.cs:line 1399
   at Witty.Popup.MainGrid_MouseLeftButtonUp(Object sender,
MouseButtonEventArgs e) in
C:\wittytwitter-read-only\Witty\Witty\Popup.xaml.cs:line 117
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(RoutedEventArgs args,
RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender,
MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean
trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport
inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr
hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x,
Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr
hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd,
Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Boolean isSingleParameter, Delegate
catchHandler)
2008-04-16 13:54:24,299 [1] ERROR Witty.Logging - Unhandled exception occurred.
System.InvalidOperationException: Cannot set Visibility or call Show or
ShowDialog after window has closed.
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at Witty.MainWindow.PopupClicked(Tweet tweet) in
C:\wittytwitter-read-only\Witty\Witty\MainWindow.xaml.cs:line 1399
   at Witty.Popup.MainGrid_MouseLeftButtonUp(Object sender,
MouseButtonEventArgs e) in
C:\wittytwitter-read-only\Witty\Witty\Popup.xaml.cs:line 117
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(RoutedEventArgs args,
RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender,
MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean
trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport
inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr
hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x,
Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr
hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd,
Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Boolean isSingleParameter, Delegate
catchHandler)
[Footer]\r\n

```

Original issue reported on code.google.com by `steven.n...@gmail.com` on 16 Apr 2008 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
thanks for the heads up. we'll investigate.
```

Original comment by `alan...@gmail.com` on 16 Apr 2008 at 8:47
