### ISSUE TITLE
Unable to logon after install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#160]
```
What steps will reproduce the problem?
1. Install Witty on XP
2. Try Logging on
3. Fails

What is the expected output? What do you see instead?
Log on, instead see The Remote Server Returned Error 403

What version of the product are you using? On what operating system?
XP witty 0.1.8

Please provide any additional information below.

2008-04-09 21:04:50,353 [1] ERROR Witty.Logging - There was a problem 
launching the specified URL.
2008-04-09 22:21:19,935 [1] ERROR Witty.Logging - Unhandled exception 
occurred.
System.InvalidCastException: Unable to cast object of 
type 'TwitterLib.DirectMessage' to type 'TwitterLib.Tweet'.
   at Witty.MainWindow.get_SelectedTweet()
   at Witty.MainWindow.MainWindow_OnKeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate 
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, 
Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, 
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, 
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean 
trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport 
inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr 
hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 
scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction
(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& 
msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object 
source, Delegate callback, Object args, Boolean isSingleParameter, 
Delegate catchHandler)


```

Original issue reported on code.google.com by `robert.n...@gmail.com` on 25 Oct 2008 at 4:51

**Comment by GoogleCodeExporter** [comment]
```
Since this is a 403 error, it appears to be a dupe of 152.
```

Original comment by `james.deville` on 1 Feb 2009 at 12:53
- Changed state: **Duplicate**
