### ISSUE TITLE
Witty crashes on start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#209]
```
What steps will reproduce the problem?
1. Run the latest ClickOnce version of Witty 
2. The following error will occur.

System.TypeLoadException was unhandled
  Message="Could not load type 'TwitterLib.Utilities.UserBehaviorManager' 
from assembly 'TwitterLib, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=19392ef3ce00d32c'."
  Source="mscorlib"
  TypeName="TwitterLib.Utilities.UserBehaviorManager"
  StackTrace:
       at System.Signature._GetSignature(SignatureStruct& signature, Void* 
pCorSig, Int32 cCorSig, IntPtr fieldHandle, IntPtr methodHandle, IntPtr 
declaringTypeHandle)
       at System.Signature..ctor(Void* pCorSig, Int32 cCorSig, 
RuntimeTypeHandle declaringTypeHandle)
       at System.Reflection.RuntimePropertyInfo.get_Signature()
       at System.Reflection.RuntimePropertyInfo.get_PropertyType()
       at 
System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo 
propInfo)
       at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
       at System.Configuration.ApplicationSettingsBase.get_Properties()
       at System.Configuration.ApplicationSettingsBase.Reload()
       at Witty.App.CheckForCorruptedConfigFile()
       at Witty.App.OnStartup(StartupEventArgs e)
       at System.Windows.Application.<.ctor>b__0(Object unused)
       at 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Boolean isSingleParameter)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object 
source, Delegate callback, Object args, Boolean isSingleParameter, Delegate 
catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Threading.ExecutionContext.runTryCode(Object userData)
       at 
System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCle
anup(TryCode code, CleanupCode backoutCode, Object userData)
       at System.Threading.ExecutionContext.Run(ExecutionContext 
executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, 
Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr 
wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Boolean isSingleParameter)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object 
source, Delegate callback, Object args, Boolean isSingleParameter, Delegate 
catchHandler)
       at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority 
priority, TimeSpan timeout, Delegate method, Object args, Boolean 
isSingleParameter)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, 
IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at 
System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame 
frame)
       at System.Windows.Application.RunInternal(Window window)
       at Witty.App.Main()
  InnerException: 


Running Windows Vista Ultimate.


```

Original issue reported on code.google.com by `judahgab...@gmail.com` on 31 Jan 2009 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
Reinstalling the application fixed this issue. Feel free to close this.
```

Original comment by `judahgab...@gmail.com` on 1 Feb 2009 at 6:32

**Comment by GoogleCodeExporter** [comment]
```
Closing by request and with no apparent repro.
```

Original comment by `james.deville` on 8 Feb 2009 at 7:44
- Changed state: **Fixed**
