### ISSUE TITLE
witty after start crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#236]
```
What steps will reproduce the problem?
1. Click on witty icon
2. Show message box with "Witty has encountered an unexpected error. Please
restart Witty"
3. Show vista dialog with information about program crash

Description:
  Stopped working

Problem signature:
  Event Type:   CLR20r3
  P01:  witty.exe
  P02:  2.1.0.540
  P03:  497ec338
  P04:  System.Configuration
  P05:  2.0.0.0
  P06:  4889de74
  P07:  1a8
  P08:  75
  P09:  IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
  OS Version:   6.0.6001.2.1.0.256.1
  Locale ID:  1029

```

Original issue reported on code.google.com by `michal.t...@gmail.com` on 1 Mar 2009 at 7:52

**Comment by GoogleCodeExporter** [comment]
```
I get the same thing with v2.1.0 or the nightly build (4/29/2009).

Description:
  Stopped working

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: witty.exe
  Problem Signature 02: 2.2.0.23807
  Problem Signature 03: 49f7717f
  Problem Signature 04: PresentationFramework
  Problem Signature 05: 3.0.0.0
  Problem Signature 06: 48fef62a
  Problem Signature 07: 625a
  Problem Signature 08: e1
  Problem Signature 09: System.Windows.Markup.XamlParse
  OS Version:   6.0.6001.2.1.0.256.1
  Locale ID:    1033
```

Original comment by `d.ru...@gmail.com` on 8 May 2009 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
Here's from the log:

[Header]\r\n2009-05-07 23:21:10,946 [1] INFO  Witty.Logging - Witty is starting.
2009-05-07 23:21:11,031 [1] ERROR Witty.Logging - Unhandled Exception
System.Windows.Markup.XamlParseException: Cannot convert string '1,0,1,1' in 
attribute 'BorderThickness' to object of type 'System.Windows.Thickness'. 
'1,0,1,1' 
string cannot be converted to Length.  Error at object 
'System.Windows.Controls.ControlTemplate' in markup file 
'CustomWindow;component/windowbutton.xaml'. ---> System.FormatException: 
'1,0,1,1' 
string cannot be converted to Length.
   at System.Windows.LengthConverter.FromString(String s, CultureInfo cultureInfo)
   at System.Windows.ThicknessConverter.FromString(String s, CultureInfo cultureInfo)
   at System.Windows.ThicknessConverter.ConvertFrom(ITypeDescriptorContext 
typeDescriptorContext, CultureInfo cultureInfo, Object source)
   at System.Windows.Markup.XamlTypeMapper.ParseProperty(Object targetObject, Type 
propType, String propName, Object dpOrPiOrFi, ITypeDescriptorContext 
typeContext, 
ParserContext parserContext, String value, Int16 converterTypeId)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlParseException.ThrowException(String message, 
Exception innerException, Int32 lineNumber, Int32 linePosition, Uri baseUri, 
XamlObjectIds currentXamlObjectIds, XamlObjectIds contextXamlObjectIds, Type 
objectType)
   at System.Windows.Markup.XamlParseException.ThrowException(ParserContext 
parserContext, Int32 lineNumber, Int32 linePosition, String message, Exception 
innerException)
   at System.Windows.Markup.BamlRecordReader.CreateInstanceFromType(Type type, Int16 
typeId, Boolean throwOnFail)
   at 
System.Windows.Markup.BamlRecordReader.GetElementAndFlags(BamlElementStartRecord

bamlElementStartRecord, Object& element, ReaderFlags& flags, Type& 
delayCreatedType, 
Int16& delayCreatedTypeId)
   at 
System.Windows.Markup.BamlRecordReader.BaseReadElementStartRecord(BamlElementSta
rtRec
ord bamlElementRecord)
   at 
System.Windows.Markup.BamlRecordReader.ReadElementStartRecord(BamlElementStartRe
cord 
bamlElementRecord)
   at System.Windows.Markup.BamlRecordReader.ReadRecord(BamlRecord bamlRecord)
   at System.Windows.Markup.BamlRecordReader.Read(Boolean singleRecord)
   at System.Windows.Markup.TreeBuilderBamlTranslator.ParseFragment()
   at System.Windows.Markup.TreeBuilder.Parse()
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext 
parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, 
ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, 
Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate 
callback, Object args, Boolean isSingleParameter, Delegate catchHandler)


It looks like Witty is not compatible with different locale formatting.  I use 
" " as 
the thousand separator and "," as the decimal point, i.e. 1,234,567.89 = 1 234 
567,89
```

Original comment by `d.ru...@gmail.com` on 8 May 2009 at 3:23
