### ISSUE TITLE
Not working / logging anymore. Getting an "Witty has encountered an expected error. Please restart Witty" error 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#304]
```
What steps will reproduce the problem?
1.Trying to log in and then getting an "Witty has encountered an expected 
error. Please restart Witty" msg

What is the expected output? What do you see instead?
regular login.

What version of the product are you using? On what operating system?
Last version of Witty (Setup-Witty-2.4.0.exe) / Windows 7

Please provide any additional information below.

Log file has the following error:
2010-09-01 13:39:20,940 [1] ERROR Witty.Logging - Unhandled exception occurred.
System.Reflection.TargetInvocationException: Exception has been thrown by the 
target of an invocation. ---> System.Security.SecurityException: Not Authorized.
   at TwitterLib.TwitterNet.ParseWebException(WebException webExcp, Nullable`1 timeline, String userId) in C:\Projects\Jon\WittyTwitter\Witty\TwitterLib\TwitterNet.cs:line 1482
   at TwitterLib.TwitterNet.ParseWebException(WebException webExcp) in C:\Projects\Jon\WittyTwitter\Witty\TwitterLib\TwitterNet.cs:line 1457
   at TwitterLib.TwitterNet.Login() in C:\Projects\Jon\WittyTwitter\Witty\TwitterLib\TwitterNet.cs:line 954
   at Witty.LoginControl.TryLogin(TwitterNet twitter)
The Zone of the assembly that failed was:
MyComputer
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```

Original issue reported on code.google.com by `cadbu...@gmail.com` on 1 Sep 2010 at 4:58
- Merged into: #271

**Comment by GoogleCodeExporter** [comment]
```
This is probably related to issue 271  
http://code.google.com/p/wittytwitter/issues/detail?id=271  that non OAuth 
calls will be blocked.
```

Original comment by `fields.trevor@gmail.com` on 2 Sep 2010 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
Yes, this is a duplicate of 271
```

Original comment by `jongallo...@gmail.com` on 2 Sep 2010 at 5:16
- Changed state: **Duplicate**
