### ISSUE TITLE
TwitterLib/Witty crashes on malformed Xml from Twitter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emuikernel/wittytwitter#72]
```
1.  Run Witty when twitter is having difficulties.

Using 1.6 beta, downloaded today.  After spitting back server 500 errors, 
twitter stabilized around 4:10AM EST.  After another 5 or 6 minutes, it 
was doing an update and the doc.Load(reader) line threw XmlException.

Given the recent trouble, I think a TwitterProblemsException might be a 
good idea, given that theres already a RateLimitException.

Full Error From VS.NET 2008 Debugger:

System.Xml.XmlException was unhandled by user code
  Message="Data at the root level is invalid. Line 1, position 1."
  Source="System.Xml"
  LineNumber=1
  LinePosition=1
  SourceUri=""
  StackTrace:
       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
       at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
       at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       at System.Xml.XmlTextReaderImpl.Read()
       at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, 
Boolean preserveWhitespace)
       at System.Xml.XmlDocument.Load(XmlReader reader)
       at System.Xml.XmlDocument.Load(TextReader txtReader)
       at TwitterLib.TwitterNet.RetrieveTimeline(Timeline timeline, String 
since, String userId) in C:\Witty\Witty\TwitterLib\TwitterNet.cs:line 920
       at TwitterLib.TwitterNet.RetrieveTimeline(Timeline timeline, String 
since) in C:\Witty\Witty\TwitterLib\TwitterNet.cs:line 840
       at TwitterLib.TwitterNet.RetrieveTimeline(Timeline timeline) in 
C:\Witty\Witty\TwitterLib\TwitterNet.cs:line 831
       at TwitterLib.TwitterNet.GetFriendsTimeline() in 
C:\Witty\Witty\TwitterLib\TwitterNet.cs:line 380
       at Witty.MainWindow.GetTweets() in 
C:\Witty\Witty\Witty\MainWindow.xaml.cs:line 191
       at 
System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage
(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean 
fExecuteInContext, Object[]& outArgs)
       at 
System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage
(RuntimeMethodHandle md, Object[] args, Object server, Int32 methodPtr, 
Boolean fExecuteInContext, Object[]& outArgs)
       at 
System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage
(IMessage msg, IMessageSink replySink)
  InnerException:  
```

Original issue reported on code.google.com by `david.so...@gmail.com` on 31 Jan 2008 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
twitter is undergoing some backend changes that's killing twitter api 
reliability.
I'm going to sit on this for a day or two for the twitter servers to be 
stabilizes. 
If it doesn't then I'll look into contingency plans for malformed xml from 
twitter.

Great idea about the TwitterProblemsException.
```

Original comment by `alan...@gmail.com` on 31 Jan 2008 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
Twitter API has stabilized in the past year. Closing.
```

Original comment by `jongallo...@gmail.com` on 16 Feb 2009 at 1:06
- Changed state: **WontFix**
